replicas: 3
service:
  name: http
  port: 80
application:
  name: backend-app
  namespace: backend
  version: v1.0.0
  image: nginxdemos/hello
  tag: latest
  imagePullPolicy: IfNotPresent
  port: 80

gateway:
  name: external-lb-gateway
  namespace: envoy-gateway-system

routes:
  - protocol: http
    pathPrefix: /backend-app
    urlRewrite:
      PathPrefix: /
  

