  # ==============================================================================
  # MODULE COMPONENT: Envoy gateway API
  # DESCRIPTION: Envoy gateway configurations
  # ==============================================================================
namespace: envoy-gateway-system
class:
  name: envoy-gateway-class
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
envoyProxy:
  name: envoy-proxy-service
  group: gateway.envoyproxy.io
  kind: EnvoyProxy
  lb_targetGroup_port: 31234
  healthCheck_port: 19003
  lb_healthCheck_port: 31903
gateway:
  name: external-lb-gateway
# ==============================================================================
  # MODULE COMPONENT: Envoy gateway API
  # DESCRIPTION: Application Routes
# ==============================================================================

